# Render configuration file
services:
  - type: web
    name: quiz-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.11.7
    disk:
      name: quiz-data-disk
      mountPath: /opt/render/project/src
      sizeGB: 1

