# Render configuration file - DISABLED (use manual settings in Dashboard instead)
# Problem: Root directory mismatch
# Solution: Set Root Directory manually in Render Dashboard to "Backend" or leave empty

# services:
#   - type: web
#     name: quiz-backend
#     env: python
#     region: frankfurt
#     plan: free
#     buildCommand: pip install -r requirements.txt && python -m pip install --upgrade pip
#     startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
#     envVars:
#       - key: PYTHON_VERSION
#         value: 3.11.7

